### ISSUE TITLE
DataModel

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/grimwild#2]
# Actor Types
- Character
- NPC
- Party

# Item Types
- Ability

## Character

```yaml
- details
  - name: String
  - ancestry: String
  - backgrounds: String
  - look: String
- stats
  - str:
    - value: Number
    - condition: Boolean
  - agi:
    - value: Number
    - condition: Boolean
  - wit:
    - value: Number
    - condition: Boolean
  - pre:
    - value: Number
    - condition: Boolean
# (more TBD)
```
